export function createOpsRoomFixture(overrides = {}) {
  return {
    contract_version: 1,
    revision: 42,
    generated_at: "2026-08-29T08:00:00.000Z",
    health: { hub: "ready", orca: "observed", codex: "ready" },
    room: {
      channels: [
        { id: "all", project_id: null, label: "전체", count: 2 },
        {
          id: "project:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          project_id: "project:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          label: "Buzz 통합",
          count: 1,
        },
      ],
      selected_channel_id: "project:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      threads: [
        {
          id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          type: "work",
          work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          session_id: null,
          project_id: "project:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          title: "네이티브 Agent Room",
          status: "in_progress",
          provider: "codex",
          updated_at: "2026-08-29T08:00:00.000Z",
          session_count: 4,
          approval_count: 1,
          artifact_count: 1,
        },
        {
          id: "session:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
          type: "session",
          work_item_id: null,
          session_id: "session:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
          project_id: null,
          title: "기타 세션",
          status: "waiting",
          provider: "orca",
          updated_at: "2026-08-29T07:00:00.000Z",
          session_count: 1,
          approval_count: 0,
          artifact_count: 0,
        },
      ],
      selected_thread_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      messages: [
        {
          id: "event:dddddddddddddddddddddddddddddddd",
          kind: "completion",
          timestamp: "2026-08-29T08:04:00.000Z",
          role: "agent",
          author: "Codex sub",
          body: "컴포넌트 구현과 검증을 완료했습니다.",
          details: { source: "codex_sub", outcome: "완료", tests: 18 },
        },
        {
          id: "event:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
          kind: "delegation",
          timestamp: "2026-08-29T08:01:00.000Z",
          role: "orchestrator",
          author: "Orca",
          body: "네이티브 UI 구현을 Codex에 위임했습니다.",
          details: { source: "orca", outcome: "위임됨" },
        },
        {
          id: "event:cccccccccccccccccccccccccccccccc",
          kind: "status",
          timestamp: "2026-08-29T08:02:00.000Z",
          role: "agent",
          author: "Codex",
          body: "반응형 레이아웃을 구현하고 있습니다.",
          details: { source: "codex_direct", outcome: "진행 중" },
        },
        {
          id: "event:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
          kind: "question",
          timestamp: "2026-08-29T08:03:00.000Z",
          role: "agent",
          author: "Claude Code",
          body: "접근성 검토가 필요합니다.",
          details: { source: "claude_code", outcome: "검토 필요" },
        },
        {
          id: "event:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          kind: "artifact",
          timestamp: "2026-08-29T08:02:00.000Z",
          role: "agent",
          author: "Codex",
          body: "UI 검토 아티팩트를 만들었습니다.",
          details: { source: "codex_direct", outcome: "생성됨" },
        },
        {
          id: "event:ffffffffffffffffffffffffffffffff",
          kind: "approval",
          timestamp: "2026-08-29T08:05:00.000Z",
          role: "system",
          author: "Hub",
          body: "외부 전달은 비활성화되어 있습니다.",
          details: { source: "hub", outcome: "승인 필요" },
        },
      ],
      context: {
        work_item: {
          id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          project_id: "project:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          title: "네이티브 Agent Room",
          status: "in_progress",
          progress: 72,
          last_activity_at: "2026-08-29T08:05:00.000Z",
          execution_provider: "codex",
          provider_model: "gpt-5.6",
          provider_effort: "high",
          revision: 9,
          updated_at: "2026-08-29T08:05:00.000Z",
        },
        provider_run: {
          id: "run:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          provider: "codex",
          model: "gpt-5.6",
          provider_effort: "high",
          provenance: {
            source: "master_assignment",
            source_ref: "event:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          },
          session_id: "codex_direct:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          status: "running",
          approval_id: "approval:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          revision: 3,
          created_at: "2026-08-29T08:00:00.000Z",
          updated_at: "2026-08-29T08:05:00.000Z",
        },
        sessions: [
          {
            id: "codex_direct:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            project_id: "project:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            parent_session_id: null,
            title: "Codex 직접 세션",
            agent: "Codex",
            activity: "implementing",
            health: "active",
            health_reason: null,
            last_activity_at: "2026-08-29T08:05:00.000Z",
            execution_provider: "codex",
            provider_model: "gpt-5.6",
            provider_effort: "high",
            revision: 3,
            updated_at: "2026-08-29T08:05:00.000Z",
          },
        ],
        approvals: [
          {
            id: "approval:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            target_session_id: "codex_direct:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            draft_text: "외부 전달 초안",
            action_kind: "deliver",
            status: "held",
            hold_reason: "external_action_disabled",
            risk_class: ["external"],
            risk_targets: ["teams"],
            approved_at: null,
            revision: 1,
            updated_at: "2026-08-29T08:05:00.000Z",
          },
        ],
        artifacts: [
          {
            id: "artifact:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            title: "Agent Room UI 검토",
            kind: "html",
            status: "ready",
            version: 1,
            source_event_id: "event:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            created_at: "2026-08-29T08:04:00.000Z",
            updated_at: "2026-08-29T08:04:00.000Z",
          },
        ],
      },
      extensions: {},
    },
    session_tree: [
      {
        id: "orca:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        source: "orca",
        parent_session_id: null,
        work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        title: "Orca 디스패치",
        activity: "delegating",
        health: "active",
        last_activity_at: "2026-08-29T08:05:00.000Z",
        child_ids: [],
      },
      {
        id: "codex_direct:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        source: "codex_direct",
        parent_session_id: null,
        work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        title: "Codex 직접 세션",
        activity: "implementing",
        health: "active",
        last_activity_at: "2026-08-29T08:05:00.000Z",
        child_ids: ["codex_sub:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"],
      },
      {
        id: "codex_sub:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        source: "codex_sub",
        parent_session_id: "codex_direct:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        title: "반응형 UI",
        activity: "testing",
        health: "active",
        last_activity_at: "2026-08-29T08:04:00.000Z",
        child_ids: [],
      },
      {
        id: "claude_code:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        source: "claude_code",
        parent_session_id: null,
        work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        title: "접근성 검토",
        activity: "reviewing",
        health: "waiting",
        last_activity_at: "2026-08-29T08:03:00.000Z",
        child_ids: [],
      },
    ],
    checklist: [
      {
        id: "checklist:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        work_item_id: "work:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        title: "반응형 레이아웃 검증",
        status: "in_progress",
        order: 1,
      },
    ],
    decisions: [
      {
        id: "event:99999999999999999999999999999999",
        queue: "agent_autonomous",
        source: "checklist",
        title: "구현 계속",
        question: "다음 검증 단계로 진행합니다.",
        item_id: "checklist:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      },
    ],
    module_states: {
      timeline: { status: "unavailable" },
      approvals: { status: "unavailable" },
      artifacts: { status: "unavailable" },
      connections: { status: "unavailable" },
      workflow_routing: { status: "unavailable" },
      research: { status: "unavailable" },
      repositories: { status: "unavailable" },
    },
    ...overrides,
  };
}
